import type { Metadata } from "next";
import { Inter, Poppins } from "next/font/google";
import I18nProvider from "./components/I18nProvider";
import i18n from '@/i18n'

import Navbar from "./components/Navbar";
import Footer from "./components/Footer";

import "./globals.css";
import "slick-carousel/slick/slick.css";
import "slick-carousel/slick/slick-theme.css";



const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
});

const poppins = Poppins({
  subsets: ["latin"],
  variable: "--font-poppins",
  weight: "100"
});

export const metadata: Metadata = {
  title: "Camberfarms Africa",
  description: "Generated by create next app",
};

type Props = {
  children: React.ReactNode;
  params: {
    locale: string;
  };
};

export default async function RootLayout({ children, params }: {children: React.ReactNode; params: Promise<{locale:string}>}) {


  return (
    <html lang="en">
      <body className={`${inter.variable} ${poppins.variable} antialiased`}>
        <I18nProvider>
          <div className="xl:hidden block">
            <Navbar logoSrc="/images/logo.png" />
          </div>

          {children}

          <Footer />
        </I18nProvider>
      </body>
    </html>
  );
}
